### ISSUE TITLE
Usage of plugin

### ISSUE THREAD

**Issue by ashishkatoch** [cakephp/acl#101]
Hello There,

I am new in cake php. I have successfully installed ACL as well as database tables following your instruction in my cake php 3.0 website. But I don't aware that  how to use it further on my website.Can you please let me know the instruction of implementation ?

Regards
Ashish K.

**Comment by ribafs** [comment]
See here:
http://junalontherun.com/2010/11/27/a-simple-cakephp-access-control-list-acl-tutorial/

**Comment by aagasi** [comment]
Hi there, i'm using this plugin and had no problem so far. 

The thing is that i just imported some users to my database and when i tried to edit one of them i get this error: 

AclNode::node() - Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => 100 ) "

It seems like in the importing process i forgot to hit the acl tables...but the thing is that i don't know if it is there a way to say to the plugin "hey, update the references to my users" or something like that.

Thanks for any hint.

**Comment by zledwon** [comment]
Proper, official documentation would be in place.

**Comment by BassemN** [comment]
:+1: for official documentation

**Comment by josegonzalez** [comment]
@zledwon would you be interested in helping to get us started there?

**Comment by zledwon** [comment]
@josegonzalez I wish I was able to help, but my knowledge about this Acl plugin is too weak :/
I really appreciate the amount of work you've put into this plugin 👍

**Comment by yark** [comment]
Huge piece of information for understanding background can be found in [2.0 book](https://book.cakephp.org/2.0/en/core-libraries/components/access-control-lists.html)

**Comment by kgbph** [comment]
The AuthComponent was recently deprecated.
Anyone has idea for integrating ACL with the authorization plugin?

**Comment by othercorey** [comment]
Please follow up in slack or discourse.

**Comment by ribafs** [comment]
If you are using version 3 try this plugin
https://github.com/ribafs/admin-br
