### ISSUE TITLE
BindNode

### ISSUE THREAD

**Issue by golgher** [cakephp/acl#109]
In cakephp 2.x it's possible to bind user to the group's Aro, thus when a user is save, the acl component will bind the user record to the group's Aro record. In authorization the user will be bind to the group's Aro too.
But in cakephp 3.x this feature is not avaiable.

**Comment by Xety** [comment]
You means to manage the ACL with a Group and not the Users directly ? If yes, than it's available.
You need of course a *Groups* table and a field `group_id` in the *Users* table.

**AppControler.php**
``` php
public function initialize()
{
    parent::initialize();

    $this->loadComponent('Acl.Acl');
    $this->loadComponent('Auth', [
        'className' => 'AclAuth',
        'authorize' => [
            'Acl.Actions' => [
                'actionPath' => 'controller/'
            ]
        ]
    ]);
}
```

**UsersTable.php**
``` php
public function initialize(array $config)
{
    $this->addBehavior('Acl.Acl', [
        'type' => 'requester',
        'enabled' => false
    ]);
}
```

**User.php** (Entity)
```php
public function parentNode()
{
    if (!$this->id) {
        return null;
    }
    if (isset($this->group_id)) {
        $groupId = $this->group_id;
    } else {
        $Users = TableRegistry::get('Users');
        $user = $Users->find('all', ['fields' => ['group_id']])->where(['id' => $this->id])->first();
        $groupId = $user->group_id;
    }

    if (!$groupId) {
        return null;
    }

    return ['Groups' => ['id' => $groupId]];
}
```

**GroupsTable.php**
``` php
public function initialize(array $config)
{
    $this->addBehavior('Acl.Acl', [
        'type' => 'requester'
    ]);
}
```

**Group.php** (Entity)
```php
public function parentNode()
{
    return null;
}
```

You can find an example of this implementation in my project [Xeta](https://github.com/Xety/Xeta).

**Comment by golgher** [comment]
@Xety , 
your example was perfect for my case, Thanks!
