### ISSUE TITLE
how to use Acl with JWT

### ISSUE THREAD

**Issue by leandrofreires** [cakephp/acl#124]
How to use ADmad/cakephp-jwt-auth with acl

I set up all the acl and authentication but by doing a get it returns me
AclNode :: node () - Could not find Aros node identified by "Array ([Aros0.model] => Users [Aros0.foreign_key] => 1)"

My controller

$this->loadComponent('Auth', [ 'authorize' => [ 'Acl.Actions' => ['actionPath' => 'controllers/'] ], 'authenticate' => [ AuthComponent::ALL => ['userModel' => 'Employes'], 'Form' => [ 'fields' => [ 'username' => 'email', 'password' => 'senha' ], 'scope' => ['Employes.status' => 1] ], 'ADmad/JwtAuth.Jwt' => [ 'parameter' => 'token', 'scope' => ['Employes.status' => 1], 'queryDatasource' => true ] ], 'unauthorizedRedirect' => false, 'checkAuthIn' => 'Controller.initialize', 'storage' => 'Memory' ]);

The name of my tables employes and roles where they are configured

Employes entity
public function parentNode() { if (!$this->id) { return null; } if (isset($this->role_id)) { $roleId = $this->role_id; } else { $employes = TableRegistry::get('Employes'); $employes = $employes->find('all', ['fields' => ['role_id']])->where(['id' => $this->id])->first(); $roleId = $employes->role_id; } if (!$roleId) { return null; } return ['Roles' => ['id' => $roleId]]; }

**Comment by dakota** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP ACL plugin. If you are
looking for help on how to implement a feature or to better understand
how to use the plugin correctly, please visit one of the following:
 
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
