### ISSUE TITLE
Upgrade deprecated

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/acl#132]
Cake\Network\Request is deprecated, are you guys planning on upgrade this plugin?

https://github.com/cakephp/acl/blob/4f218cd2fb6d92cc3f44b9342db6a6cfa4b87c48/src/Auth/ActionsAuthor
ize.php#L17

**Comment by markstory** [comment]
Personally I am not. We will be focusing effort on a new Authorization plugin that provides a more generalized way to implement access control that doesn't use the existing DbAcl feature set.

**Comment by josegonzalez** [comment]
@rochamarcelo if you would like to make pull requests to remove the deprecated usages, that would be great :)

**Comment by rochamarcelo** [comment]
@josegonzalez I'll take a time for it.
