### ISSUE TITLE
Are ACL queries cached?

### ISSUE THREAD

**Issue by arilia** [cakephp/acl#135]
Every time I reload a page in my application I see that 6 queries are fired in order to check permissions for the action being requested

I can see them when I have debug=true and debugKit enabled.

Maybe I'm wrong but I remember that it hasn't always been this way: I remember the queries used to be somehow cached and been performed just once in a while.

In can't recall since when this behavior has changed (if it has changed at all)

Has something changed? Am I confusing? Is there a way to enable caching of permissions since they don't change very often?

My configuration:
Cakephp 3.5.12 
ACL 0.2.6 (DBAcl on a MySql Server)
DebugKit 3.14.1

**Comment by raul338** [comment]
For the main query for controller/action check, i don't know if that can be cached.
For links that should display or not if the user has those actions allowed, I use [this helper](https://github.com/shahonseven/CakePHP-AclLinkHelper/tree/3.x) which uses cache

**Comment by markstory** [comment]
> Has something changed? Am I confusing? 

Nope it has always worked this way.

> Is there a way to enable caching of permissions since they don't change very often?

Not in this plugin there isn't.

**Comment by arilia** [comment]
@rchavik No, I didn't even know it existed and I don't know how to enabled it.

Does it do what the name suggest? Why @markstory says that there is no way to cache in this plugin?

**Comment by rchavik** [comment]
afaik you enable it by doing Configure::write('Acl.className',  'CachedDb')

**Comment by arilia** [comment]
@rchavik thanks, it works
