### ISSUE TITLE
compatibity with 3.6.0

### ISSUE THREAD

**Issue by arilia** [cakephp/acl#137]
After upgrading to 3.6.0 I receive many warnings about this plugin

Is there a plan to resolve the deprecation warnings?

edit: now I see that the deprecations has been resolved in the master branch, but still I see them in my application even after running composer update. I see that the installed version is 0.2.6

**Comment by markstory** [comment]
I can tag a new release.

**Comment by markstory** [comment]
0.3.0 released.

**Comment by arilia** [comment]
Thank you very much. 

I upgraded and it solved a lot of warnings but I still get a couple of messages:

> Deprecated (16384): The ArrayAccess methods will be removed in 4.0.0.Use getParam() instead. - /var/www/sic3/vendor/cakephp/acl/src/Auth/BaseAuthorize.php, line: 63

**Comment by markstory** [comment]
I don't have much time to work on this plugin anymore. But I'm happy to merge any pull requests people submit.

**Comment by ceeram** [comment]
PR up https://github.com/cakephp/acl/pull/139
