### ISSUE TITLE
Warning in PermissionsTable with php 7.3

### ISSUE THREAD

**Issue by chtheis** [cakephp/acl#149]
PHP 7.3 complains about the "continue" in PermissionsTable line 144:
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

I guess the "continue" is intended to continue with the foreach loop and thus could be replaced by break and make all version of PHP happy.

**Comment by chtheis** [comment]
PHP 7.3 is the default version of Debian "Buster". 
I switched to Buster because the default of stable / Stretch is still 7.0 (or maybe 7.1)

**Comment by zortje** [comment]
Any plans on tagging a release to include this fix ?
