### ISSUE TITLE
Trying to access protected property in AclExtrasShell.php

### ISSUE THREAD

**Issue by DJansen20** [cakephp/acl#155]
In version 0.5.0 and CakePHP 3.7 the following exception is thrown:
[Error] Cannot access protected property Acl\AclExtras::$Shell in vendor/cakephp/acl/src/Shell/AclExtrasShell.php on line 63

When changing line 63 from `$this->AclExtras->Shell = $this;` to `$this->AclExtras->setShell($this);` the shell is correctly set.

**Comment by dakota** [comment]
Can you open a PR for this?

**Comment by dakota** [comment]
Fixed in 0.5.1. Sorry about that!
