### ISSUE TITLE
PHP 7.4 deprecation warnings for curly braces in PermissionsTable

### ISSUE THREAD

**Issue by frankvanhest** [cakephp/acl#160]
I'm using the latest release of this repository. I just switched to PHP 7.4 and I'm getting two deprecation warnings for `Array and string offset access syntax with curly braces is deprecated` on lines 185 and 192 of the `Acl\Model\Table\PermissionsTable`.

Hopefully this will be resolved in the next release of the ACL.

**Comment by saeideng** [comment]
would you like to open a Pull Request ?

**Comment by frankvanhest** [comment]
A PR is not needed anymore, someone beat me to it ;) #161
