### ISSUE TITLE
Performance in the Aco and Aro tables

### ISSUE THREAD

**Issue by alexsmonte** [cakephp/acl#168]
Hey guys,

I'm using ACL to control my application.

I use it in the flavour of ACL "controlled"
My user model $actsAs = array('Acl' => array('requester'));

When I was building the application with 10 users and 5 groups
everything was working fine.

Every user belongsTo a group.

I then inserted 11,000 records in my user table... and all actions
that require ACL check in the ARO/ACO table are really slow!

Here an example of the queries that slow down the application:

takes 5502 ms
```sql
SELECT `Aro`.`id`, `Aro`.`parent_id`, `Aro`.`model`,
`Aro`.`foreign_key`, `Aro`.`alias` FROM `aros` AS `Aro` LEFT JOIN
`aros` AS `Aro0` ON (`Aro`.`lft` <= `Aro0`.`lft` AND `Aro`.`rght` >=
`Aro0`.`rght`) WHERE `Aro0`.`model` = 'User' AND `Aro0`.`foreign_key`
= 1 ORDER BY `Aro`.`lft` DESC
```

takes 628 ms
```sql
SELECT `Aco`.`id`, `Aco`.`parent_id`, `Aco`.`model`,
`Aco`.`foreign_key`, `Aco`.`alias` FROM `acos` AS `Aco` LEFT JOIN
`acos` AS `Aco0` ON (`Aco0`.`alias` = 'controllers') LEFT JOIN `acos`
AS `Aco1` ON (`Aco1`.`lft` > `Aco0`.`lft` AND `Aco1`.`rght` <
`Aco0`.`rght` AND `Aco1`.`alias` = 'Crags') LEFT JOIN `acos` AS `Aco2`
ON (`Aco2`.`lft` > `Aco1`.`lft` AND `Aco2`.`rght` < `Aco1`.`rght` AND
`Aco2`.`alias` = 'admin_index') WHERE ((`Aco`.`lft` <= `Aco0`.`lft`
AND `Aco`.`rght` >= `Aco0`.`rght`) OR (`Aco`.`lft` <= `Aco2`.`lft` AND
`Aco`.`rght` >= `Aco2`.`rght`)) ORDER BY `Aco`.`lft` DESC
```

This is a demo structure of my aro table (with just 7 records out of
11,000): 

**Solution by Jon Bennet – in cakegroup - google in 2011**

```sql
CREATE INDEX idx_acos_lft_rght ON `acos`(lft,rght);
CREATE INDEX idx_acos_alias ON `acos`(alias);
CREATE INDEX idx_acos_model_foreign_key ON `acos`(model(255),foreign_key);

CREATE INDEX idx_aros_lft_rght ON `aros`(lft,rght);
CREATE INDEX idx_aros_alias ON `aros`(alias);
CREATE INDEX idx_aros_model_foreign_key ON `aros`(model(255),foreign_key);

CREATE UNIQUE INDEX idx_aros_acos_aro_id_aco_id ON `aros_acos`(aro_id, aco_id);
ALTER TABLE aros_acos ADD CONSTRAINT FOREIGN KEY (aro_id) REFERENCES `aros`(id);
ALTER TABLE aros_acos ADD CONSTRAINT FOREIGN KEY (aco_id) REFERENCES `acos`(id);
```

**Comment by markstory** [comment]
I am not entirely sure what your goal is with this issue. It sounds like you found a solution to make your queries more efficient.

**Comment by alexsmonte** [comment]
It was just registered, I needed it in 2011 in version 1.3 and had to resort to google's cache, it may be that somebody needs it too.

**Comment by zahari4i** [comment]
> It was just registered, I needed it in 2011 in version 1.3 and had to resort to google's cache, it may be that somebody needs it too.

Thank you, I was searching for a solution for days. It seems the ACL plugin has problems when these tables grow in size. I have about 8000 users in the DB and about 10000 records in the aros table. The first query you mentioned was taking about 20 to 30 seconds on production (dedicated managed mysql 5.7 instance) and just a bit less on localhost (mysql 8 on i9 macbook pro). I was playing around with indexes but nothing helped. 
It seem the index that did the trick was:
CREATE INDEX idx_aros_model_foreign_key ON `aros`(model(255),foreign_key);

I believe this should be addressed and I'm curious why there are only a couple of people facing this problem. 10000 users seem a very small number to me.
