### ISSUE TITLE
AclShell delete fail because entity ORM thinks it is new record

### ISSUE THREAD

**Issue by sarrala** [cakephp/acl#36]
1. Created empty db tables.
2. Created root aro node through shell.
3. Deleted node: cake acl.acl delete aro Test
4. Expected results: row deleted from database.
5. Actual results: error message.

Node was found with id 2 but can't be deleted because Entity thinks it's new.
Everything goes as it should until ORM/Table instructs _processDelete caller to rollback.

Not sure if this is cakephp / ORM / Entity issue or ACL plugin issue.

@ORM/Table / _processDelete:
```php
....
    protected function _processDelete($entity, $options)
    {
        if ($entity->isNew()) {
            return false;
        }
....
```

**Comment by Xety** [comment]
It's ACL related. If you can do a PR, just change this line :
https://github.com/cakephp/acl/blob/master/src/Shell/AclShell.php#L158
to
```php
$entity = $this->Acl->{$class}->get($nodeId);
```
Else, if you can't do a PR, i will do it today or tomorrow.
