### ISSUE TITLE
aclExtras aco_sync create only prefix actions

### ISSUE THREAD

**Issue by allandiego** [cakephp/acl#48]
using ./cake acl.aclExtras aco_sync to fill the acos table outputs me a stranger log:

Welcome to CakePHP v3.0.0-RC1 Console
---------------------------------------------------------------
App : src
Path: /home/di/public_html/test/app/src/
---------------------------------------------------------------
Created Aco node: controllers/Usuarios/profile
Created Aco node: controllers/Usuarios/change_password
Created Aco node: controllers/Usuarios/index
Created Aco node: controllers/Usuarios/admin_index
Created Aco node: controllers/Usuarios/admin_edit
Created Aco node: controllers/Usuarios/admin_create
Deleted Aco node: controllers/Usuarios/profile
Deleted Aco node: controllers/Usuarios/change_password
Deleted Aco node: controllers/Usuarios/index

I have a 'Admin' prefix set, the aco_sync function create the normal and prefix Controller actions thats ok but then the normal actions are deleted

src/Controllers/Usuarios  (this actions are created and then deleted)
src/Controllers/Admin/Usuarios

I do not know if it's intentional but the App node for AppController.php is also created, i dont remember to see this on version 2.x

**Comment by rchavik** [comment]
This is likely due to the difference between 2.x and 3.x prefix handling.  Adjustments need to be made similar to #32

**Comment by dakota** [comment]
Closed as a PR is now open - #68
