### ISSUE TITLE
acl Extras Shell on Windows

### ISSUE THREAD

**Issue by geraldurbas** [cakephp/acl#67]
failes. Its using the wrong paths seperators

**Comment by rchavik** [comment]
Would you be able to submit a fix?

**Comment by estevesklein** [comment]
Suggested correction:
In the method "Acl\AclExtras\_updateControllers"
...
foreach ($ controllers the controller $) {
    $controller = str_replace (DS, '/', $ controller);

Greetings

**Comment by geraldurbas** [comment]
use https://github.com/geraldurbas/acl/blob/master/src/AclExtras.php... should work also on Linux.

**Comment by rchavik** [comment]
or submit a PR so everyone can benefit :)

**Comment by rchavik** [comment]
Fixed by #69
