### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cholnhial** [cakephp/acl#76]
Hi,

I'm just wondering if there's a documentation on how to use this plugin.

**Comment by markstory** [comment]
Currently there is only the readme. However, the behavior is mostly the same as the 2.x implementation.

**Comment by alexsmonte** [comment]
Hello n0per could "config" the ACL?

**Comment by serveait** [comment]
how to use a acl library like sentry 2 with cakephp 3.0

**Comment by serveait** [comment]
I have loaded the plugin in cake 3
it shows up in debugkit
and I am trying to load the component in app controller using following code ;
namespace Acl\Controller\Component;

use Acl\Controller\Component\AclComponent;


and 
$this->loadComponent('Acl');
and I am getting error in users/login
as 
Error: Class 'Acl\Controller\Component\Controller' not found
File /opt/lampp/htdocs/crmbake/src/Controller/AppController.php

**Comment by r0kawa** [comment]
I think it's a plugin so use

$this->loadComponent('Acl.Acl');

**Comment by alexsmonte** [comment]
users Table 

$this->addBehavior('Acl.Acl', ['type' => 'requester']);

User Entity 
 public function parentNode(){}

groups table
$this->addBehavior('Acl.Acl', ['type' => 'requester']);

group entity

    public function parentNode(){        
        return null;
    }


it will work
