### ISSUE TITLE
[3.0] Callback parentNode() not defined

### ISSUE THREAD

**Issue by macnie** [cakephp/acl#78]
I was Installed acl plugin in cakephp 3.0 by composer. but warning this:

Warning (512): Callback parentNode() not defined in \Cake\ORM\Entity [ROOT\vendor\cakephp\acl\src\Model\Behavior\AclBehavior.php, line 87]

**Comment by josegonzalez** [comment]
You need to create a `parentNode` method in the Entity. [Here is an example](https://github.com/cakephp/acl/blob/master/tests/TestCase/Model/Behavior/AclBehaviorTest.php#L59) from the tests. The general logic is the same as in CakePHP 2.x.
