### ISSUE TITLE
/ in a plugin name causes issues

### ISSUE THREAD

**Issue by Marlinc** [cakephp/acl#88]
A model stored a plugin with a / in the name causes issues with the ACL path.

**Comment by dakota** [comment]
Would you mind giving a specific test case for this?

**Comment by Marlinc** [comment]
A example would be the ```Croogo\Users.Roles``` model. This causes isues when running something like this ```./bin/cake acl check Croogo/Users.Roles.3 controllers/Croogo/Nodes/Nodes/promoted```.
In this case ```Croogo/Users.Roles``` is the model name with ```3``` being the primary key. The same happens for ```controllers/Croogo/Nodes/Nodes/promoted```, here ```Croogo/Nodes``` is the plugin name. But as you can see it gets extracted as if its part of the path/

**Comment by dakota** [comment]
Namespaced plugins use `\`, instead of `/`. Try referencing `controllers/Croogo\Nodes/Nodes/promoted` instead and see if that works?

**Comment by dakota** [comment]
This has been fixed, and works as expected.
