### ISSUE TITLE
can't login when using this

### ISSUE THREAD

**Issue by jon-h86** [cakephp/acl#98]
Hello
I have followed the simple acl app tutorial. 
Once I add the acl functionality I can't login. It keeps telling me my username and password is incorrect on every user. There might be something wrong with the plugin and cakephp 3.2.x. 
The app is making sql queries.

**Comment by markstory** [comment]
This plugin doesn't handle user logins. It handles authorization after a user has logged in. Try not using this plugin and ensuring your logins work correctly first.
