### ISSUE TITLE
Why yet "This is a non-stable plugin for CakePHP 3.0 at this time"?

### ISSUE THREAD

**Issue by mehdi-fathi** [cakephp/acl#99]
Why yet "This is a non-stable plugin for CakePHP 3.0 at this time"? I didn't install this plugin ! i was tired  , also this plugin dosen't have a good Redame for help us.I didn't run shell plugin,i had to create a plugin for acl cakephp 3.you can see my repository.that's name AclManager

**Comment by markstory** [comment]
Because no one has made the time to solidify it. What this plugin really needs is someone to maintain it that has a vested interest in making it great. I personally don't use this plugin.

**Comment by darensipes** [comment]
I used this plugin as a base for a large project I am currently working on. I find it to be very stable. My application is so custom that I made many enhancements and alternations to the Acl plugin that I am not sure the community would find useful. Example, I added the ability for field/model level authorization checks in addition to the standard ACOs. I also added an AclHelper for links and some form elements, etc, so I can control what is on menus and in templates. Then the big problems were caching the Acl using Memcache and building a permissions management tool that is easy to use.

I have used the Acl with cake over the years starting in CakePHP 1.2. The thing I have noticed and the reason I mentioned the upgrades above is, it seems every project I have to tweak and change how I need the Acl plugin to work. It is a great plugin as a base to get started, but inherently from my experience it is not a one size fits all solution. I think for that reason it adds a level of difficultly to maintain. I would be interested in forking and sharing enhancements at some point after I am finished with this project.

@markstory you mentioned that you don't use this plugin. I know many applications I have built over the years had no use for an Acl. Wondering what if anything you use as an alternative?

**Comment by markstory** [comment]
I usually end up implementing application specific authorization rules that I encapsulate into a custom Authorizer.

**Comment by mehdi-fathi** [comment]
@markstory it means you don't use rule of Acl ? it means you don't use of tables for access level ?If this right well how do you make Security on your method ?

**Comment by dakota** [comment]
We make use of it in our production application with multiple users. I'm of the opinion that it is stable. I will try to set aside some time in the coming week to deal with all the outstanding issues and pull requests and hopefully get a stable release out.

**Comment by markstory** [comment]
@mehdi-fathi I don't use database based access rules like this plugin provides. Instead I write application code that integrates with AuthComponent.

**Comment by alexsmonte** [comment]
I like the plugin, but I'm working on an improvement to it in what I believe to be interesting example:

1. I see no reason for the fields "create read update delete" there;
2. I'm working on an implementation dependencies between actions to pages that loaddata ajax;
3. Allow temporary access;

Among both times I think and there is a change to my needs and not for the whole community.

PS: Sorry for google English

**Comment by dakota** [comment]
> I see no reason for the fields "create read update delete" there;

The fields are used for the CRUD based auth adapter which allows mapping of actions to the CRUD actions.

**Comment by aagasi** [comment]
Hi guys, i'am following this plugin for a while and i dont see any progress to make it relyable and stable. I'am not a contributor developer, i'm relatively new to cakephp and i really need an ACL plugin. I started developping mine, but i think that since i'm making an effort to migrate my old application to this new framwork it would be great to save some time with a ACL plugin help.
Could anyone of you tell me if is there a chance to put this on stable mode? Or can you recommend me another plugin to manage ACL in cakephp 3.x ?

**Comment by darensipes** [comment]
I am using it in production and I feel it is stable. I am using it with the latest 3.2.x version of CakePHP. One suggestion is to fork the repo. I didn't quite fork but pulled it down and placed it with my plugins and made some customizations. I have been using the CakePHP ACL stuff for about 8 years now, the one thing I have learned is no implementation is the same, each project brings it own requirements when it comes to authorizing actions. So don't think of this plugin as a drop-in solution. Not that it can't be used as is, just don't let that limit you from customizing it to suit your needs. Example, I like to cache the permissions using memcache.

**Comment by dakota** [comment]
@aagasi I'm using it in production with no issues. It's stable in the sense that nothing breaks, but unstable in the sense that there might be a breaking api change in the future

**Comment by dakota** [comment]
I do need to update the readme file and tag a v1.0.0

**Comment by aagasi** [comment]
Thanks for the reply, both of you. I'm now making some tests with it and it would be great to see in the future some polished documentation (for newies like me) on how to start dealing with this plugin. Thanks again.

**Comment by LDSign** [comment]
@darensipes 

Hi Daren

Your modifications are really helpful - would you  mind to share your customized version of this plugin?

Thanks,
Frank

**Comment by dakota** [comment]
Closing this as a release has been tagged, and the "unstable" comment has been removed.
